[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ilp-decoder"
version = "0.1.1"
description = "ILP decoder for quantum error correction using Gurobi and cplex."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
	"numpy",
	"scipy",
	"gurobipy",
	"cplex==22.1.2.0",
	"docplex"
]

[project.optional-dependencies]
dev = [
	"pytest",
	"stim",
	"pymatching",
    "beliefmatching"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
